version: 2

jobs:

  build:
    working_directory: "~/projects/repo"

    docker:
    - image: circleci/node:8

    steps:

    - checkout

    - restore_cache:
        keys:
          - node_modules

    - run:
        command: yarn install
        no_output_timeout: 20m

    - save_cache:
       key: "node_modules"
       paths:
         - node_modules

    - persist_to_workspace:
        root: ~/projects
        paths:
          - "repo"

  deploy-uat:
    working_directory: "~/projects/repo"

    docker:
    - image: circleci/node:8

    steps:

    - attach_workspace:
        at: ~/projects

    - restore_cache:
        keys:
          - node_modules

    - run:
        command: "yarn deploy-uat"

  deploy-prd:
    working_directory: "~/projects/repo"

    docker:
    - image: circleci/node:8

    steps:

    - attach_workspace:
        at: ~/projects

    - restore_cache:
        keys:
          - node_modules

    - run:
        command: "yarn deploy-prd"

workflows:
  version: 2

  build:
    jobs:
    - build

    - deploy-uat:
        requires:
        - build
        filters:
          branches:
            only: master


    - deploy-prd:
        requires:
        - deploy-uat
        filters:
          branches:
            only: master

