version: 2
jobs:
  build:
    working_directory: ~/ciris-credstash
    machine: true
    steps:
       - checkout
       - deploy:
           name: Deploy if master branch
           command: |
             if [ "${CIRCLE_BRANCH}" == "master" -a "${CIRCLE_PROJECT_USERNAME}" == "ovotech" ]; then
               echo /dev/null | sbt "release with-defaults"
             fi
experimental:
  notify:
    branches:
      only:
        - master